<<<<<<< HEAD
theme: jekyll-theme-modernist
title: Shubham's homepage
description: Bookmark this to keep an eye on my project updates!
=======
theme: jekyll-theme-minimal
>>>>>>> fa8ea08 (academic-responsive-template)
